# Generated by Django 5.2.7 on 2025-11-01 17:19

import django.db.models.deletion
import inventry.helper_functions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_main_university_store', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=255)),
                ('register_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('register_type', models.CharField(choices=[('DEADSTOCK', 'Dead Stock Register'), ('CONSUMABLE', 'Consumable Register'), ('EQUIPMENT', 'Equipment Register')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=255, unique=True)),
                ('issued_on', models.DateField()),
                ('issued_to', models.CharField(max_length=255)),
                ('contracter', models.CharField(max_length=255)),
                ('indenter', models.CharField(max_length=255)),
                ('consignee', models.CharField(max_length=255)),
                ('date_of_delivery', models.DateField()),
                ('delivery_status', models.CharField(choices=[('PART', 'partial'), ('FULL', 'full')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventry.department')),
                ('stock_register', models.ForeignKey(help_text='Register where entries will be made', on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inventry.stockregister')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('specifications', models.JSONField(default=dict)),
                ('unit', models.CharField(max_length=50)),
                ('source_type', models.CharField(choices=[('DEPT_PURCHASE', 'Department  Purchase'), ('UNIVERSITY_STORE', 'From University Store')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventry.department')),
                ('university_master_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventry.item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventry.itemcategory')),
            ],
            options={
                'unique_together': {('code', 'department')},
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendered_quantity', models.PositiveIntegerField()),
                ('accepted_quantity', models.PositiveIntegerField()),
                ('rejected_quantity', models.PositiveIntegerField()),
                ('feed_back', models.TextField(blank=True)),
                ('create_new_item', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventry.inspectioncertificate')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventry.item')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location_type', models.CharField(choices=[('ROOM', 'Room'), ('AUDITORIUM', 'Auditorium'), ('LAB', 'Laboratory'), ('OFFICE', 'Office'), ('REPAIR_CENTER', 'Repair Center'), ('HOSTEL', 'Hostel'), ('OTHER', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventry.department')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('store_type', models.CharField(choices=[('MAIN', 'Main Department Store'), ('SUB', 'Sub  Store')], max_length=10)),
                ('location', models.TextField()),
                ('incharge_name', models.CharField(max_length=255)),
                ('incharge_contact', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventry.department')),
                ('parent_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventry.store')),
            ],
        ),
        migrations.AddField(
            model_name='stockregister',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='inventry.store'),
        ),
        migrations.CreateModel(
            name='TransferNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_note_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Receipt'), ('RECEIVED', 'Recieved'), ('PARTIAL', 'Partially Received')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out', to='inventry.store')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in', to='inventry.store')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(default=inventry.helper_functions.generate_stock_entry_code, editable=False, max_length=20, unique=True)),
                ('entry_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.PositiveIntegerField(help_text='Enter balace')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventry.item')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_entries', to='inventry.location')),
                ('stock_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventry.stockregister')),
                ('from_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_entries', to='inventry.store')),
                ('to_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_entries', to='inventry.store')),
                ('transfer_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventry.transfernote')),
            ],
        ),
        migrations.CreateModel(
            name='TransferNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('issue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_issue', to='inventry.stockentry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventry.item')),
                ('receipt_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_receipt', to='inventry.stockentry')),
                ('transfer_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventry.transfernote')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('DEPARTMENTAL_PURCHASE', 'Departmental Purchase'), ('UNIVERSITY_STORE', 'University Store Distribution')], max_length=30)),
                ('total_quantity', models.PositiveIntegerField(help_text='Total quantity received in this batch')),
                ('current_quantity', models.PositiveIntegerField(help_text='Current quantity available (unassigned units)')),
                ('warranty_period_months', models.PositiveIntegerField(default=0)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('expected_life_years', models.PositiveIntegerField(default=0)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_specifications', models.JSONField(default=dict, help_text='Specific specs for this batch')),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='inventry.inspectionitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventry.item')),
                ('source_store', models.ForeignKey(help_text='Store that created/received this batch', on_delete=django.db.models.deletion.PROTECT, related_name='batches_created', to='inventry.store')),
                ('transfer_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='inventry.transfernoteitem')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_allocated', models.PositiveIntegerField(default=0)),
                ('quantity_qr_tagged', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventry.batch')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='inventry.store')),
            ],
            options={
                'unique_together': {('store', 'batch')},
            },
        ),
    ]
