# Generated by Django 5.2.7 on 2025-11-03 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when requisition was acknowledged as received', null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='User who acknowledged receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
    ]
