# Generated by Django 5.2.7 on 2025-11-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='from_inspection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventry.inspectioncertificate'),
        ),
    ]
