# Generated by Django 5.2.7 on 2025-11-02 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0002_stockentry_from_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='stock_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='inventry.stockregister'),
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('qr_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('IN_USE', 'In Use'), ('UNDER_REPAIR', 'Under Repair'), ('WRITTEN_OFF', 'Written Off'), ('LOST', 'Lost')], default='IN_STOCK', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('tagged_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_tags', to='inventry.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assets', to='inventry.location')),
                ('current_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_assets', to='inventry.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tag_number'], name='inventry_as_tag_num_9d4357_idx'), models.Index(fields=['qr_code_uuid'], name='inventry_as_qr_code_c6698b_idx'), models.Index(fields=['status', 'current_store'], name='inventry_as_status_826b84_idx')],
            },
        ),
    ]
