# Generated by Django 5.2.7 on 2025-11-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0002_requisition_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfernoteitem',
            name='damaged_qr_tags',
        ),
        migrations.RemoveField(
            model_name='transfernoteitem',
            name='quantity_damaged',
        ),
        migrations.RemoveField(
            model_name='transfernoteitem',
            name='quantity_returned',
        ),
        migrations.RemoveField(
            model_name='transfernoteitem',
            name='quantity_short',
        ),
        migrations.RemoveField(
            model_name='transfernoteitem',
            name='return_reason',
        ),
        migrations.AlterField(
            model_name='inspectioncertificate',
            name='stock_register',
            field=models.ForeignKey(help_text='Register where entries will be made', on_delete=django.db.models.deletion.PROTECT, related_name='inspection_certificates', to='inventry.stockregister'),
        ),
    ]
