# Generated by Django 5.2.7 on 2025-11-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0003_remove_transfernoteitem_damaged_qr_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='main_stock_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventry.stockregister'),
        ),
    ]
