# Generated by Django 5.2.7 on 2025-11-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0004_alter_requisitionitem_main_stock_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventry.batch'),
        ),
    ]
